### ISSUE TITLE
Typora for Markdown - LYON的博客 | LYON's Blog

### ISSUE THREAD

**Issue by leonling-ll** [leonling-ll/LiyangLingIntel.github.io#7]
https://lyonling.github.io/2019/01/05/Typora-Markdown%E8%AF%AD%E6%B3%95/ 

 孤独是人生的常态吗？

**Comment by bingge100** [comment]
怎么导入你的博客内容到typora呢，页面不是很支持

**Comment by leonling-ll** [comment]
> @bingge100
> 怎么导入你的博客内容到typora呢，页面不是很支持

我这边主要是直接用typora去打开`_post/`目录， 然后对所有内容的编辑都在这个目录下。至于同步的问题就是命令行的git操作了，也没有什么额外的操作。但是有个问题就是typora的markdown引擎和这个博客的不太一样以至于有些效果不能实现就有些尴尬。

**Comment by bingge100** [comment]
新增文件只需要甩到——post文件就行了吧

**Comment by leonling-ll** [comment]
> @bingge100
> 新增文件只需要甩到——post文件就行了吧

dei, 记得加上yaml格式的头就好了
